---
title: "Data"
output: html_document
bibliography: ./references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Rationale 
Descripción de los recursos de datos utilizados para los análisis de los servicios ecosistémicos que existen en los robledales.

## Biodiversidad 
### Flora 

#### Comunidades vegetales OBSNEV
* Datos del seguimiento de comunidades vegetales en Sierra Nevada procedentes de OBSNEV [@Munoz2014BosquesAutoctonos] 
* Nombre de la base de datos: `./raw_data/biodiversidad/obsnev_comunidades/BD_Comunidades_v5.8_20140129.mdb` 
* 

### Fauna
#### Arachnida 
* Datos de muestreos de Arácnidos de las formaciones de Quercus en los parques nacionales de España [@Crespoetal2018DNABarcodeassisted]
* Datos: [`/EcoServ_QP/BIODIVERSIDAD/ARACNIDOS/aracnidos_spain.csv](./EcoServ_QP/BIODIVERSIDAD/ARACNIDOS/aracnidos_spain.csv)


## Provisión
### Setas 
* Datos de *Muestreos para la evaluación del recurso micológico en los principales hábitats de Andalucía*. 
    
    * Existe una publicación en el congreso Forestal Español [@RayaLopezetal2017MuestreosPara] que presenta datos de producción de setas comerzializables. 

