# pkg used
library("here")
library("tidyverse")
library("magrittr")
library("tidylog")
library("finch")
library("stringr")
library("readODS")
library("sp")
library("rgdal")
library("raster")
library("stringr")
# library("parsedate")
library("nlstools")
# library("propagate") 
library("broom")
library("sf")
library("ggspatial")
library("ggpubr")
library("gtsummary")
library("raster")
library("rasterVis")
library("RColorBrewer")
library("gridExtra")
library("ggspatial")
library("ggrepel") 
library("viridisLite")
library("patchwork")
library("grateful")


# cite_packages()

