---
title: "Plot Biomass"
output: md_document
bibliography: ../references.bib
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE, warning=FALSE}
source(here::here("load_pkgs.R"))
```

```{r, message=FALSE}
biomass_tree <- read_csv(here::here("data/biomass_trees.csv"), col_types = cols())
```

# Group by plot 
```{r}
biomass_plot <- biomass_tree %>% 
  group_by(code) %>% 
  summarise(
     ws_plot = sum(ws, na.rm=TRUE),
     wb27_plot = sum(wb27, na.rm=TRUE),
     wb2_plot = sum(wb2, na.rm=TRUE),
     wr_plot = sum(wr, na.rm=TRUE),
     h_mean = mean(h, na.rm=TRUE),
     h_min = min(h, na.rm=TRUE),
     h_max = max(h, na.rm=TRUE),
     dbh_mean = mean(dbh, na.rm=TRUE), 
     n_tree = n()
  )
```

```{r}
# Scale-up to ha and to Ton (or Megagram. 1 ton = 1 Megagram = 1000 kg )
dicc_plots <- read_csv(here::here("raw_data/dicc_plots.csv"), col_types = cols())   

biomass_plot <- biomass_plot  %>% 
  inner_join((
    dicc_plots %>% dplyr::select(
      id_plot, original_code, loc, type, size_m, size)), 
    by = c("code"="original_code"))

# ((biomasa * 10000 m2/1ha) / size) kg * 1Mg /1000 kg --> (biomasa * 10 )/size 

biomass_plot <- biomass_plot %>% 
  mutate(
    ws = (ws_plot * 10)/size,
    wb27 = (wb27_plot * 10)/size, 
    wb2 = (wb2_plot * 10)/size, 
    wr = (wr_plot* 10)/size) 

# Ojo son datos en Mg biomass / ha 
write_csv(biomass_plot, here::here("data/biomass_plot.csv"))

```


```{r}
plotsQP_selected <- st_read(here::here("/data/geoinfo/plotsQP_selected.shp"))

b <- plotsQP_selected %>% 
  inner_join(biomass_plot) %>% 
  dplyr::select(id_plot, code, project, loc, size, ws, wb27, wb2, wr, type, size_m, h_mean, h_min, h_max, dbh_mean) %>% 
  mutate(across(where(is.numeric), ~ round(., digits = 2))) %>% 
  mutate(id_plot = as.integer(id_plot)) 

st_write(b, here::here("/data/geoinfo/plotsQP_biomass.shp"), append = FALSE)
```



