---
title: "GLM_biomass"
output: md_document
bibliography: ../references.bib
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE, warning=FALSE}
source(here::here("load_pkgs.R"))
```

# Read data 
```{r, message=FALSE}
# field data 
biomass_field <- read_csv(here::here("data/biomass_plot.csv"), col_types = cols()) %>% 
  dplyr::select(code, h_mean, dbh_mean, n_tree, ba, density)
topo <- read_csv(here::here("data/topo_plots.csv"), col_types = cols()) 
shanon <- read_csv(here::here("data/shannon_str.csv"), col_types = cols())

biomass <- read_csv(here::here("data/compara_lidar_field.csv"), col_types = cols()) %>% 
  dplyr::select(id_plot, code, ws, wb27, wr, wb2, wr_lid, w2_lid, w27_lid, ws_lid, wt_lid)

df <- biomass_field %>% 
  inner_join(topo, by = "code") %>% 
  inner_join(shanon, by = "code") %>% 
  inner_join(biomass, by = "code") %>%
  filter(!is.na(wt_lid)) %>% 
  filter(code != "DIL2") # Ojo tras analizar todo el modelado he visto que hay un error en DIL2, así que lo eliminamos (era un outlier detectado con DHARMa)


```


# Explore data 

## Explore relationships 
```{r, eval=FALSE}
df %>% dplyr::select(df, wt_lid, ba, density, dem, slope, aspect, twi, sh_c2, n_strata) %>% 
  pivot_longer(cols = ba:n_strata, names_to = "variables") %>% 
  ggplot(rela, aes(y=wt_lid, x = value)) + 
  geom_point() + geom_smooth() + 
  facet_wrap(~variables, scales = "free_x")
```

## Colinealidad 
```{r}
dfs <- df %>% 
  dplyr::select(code, wt_lid, ba,density, dem, slope, aspect, twi, sh, sh_c2, n_strata) 

ggpairs(dfs, columns = 3:11) 
```


### GLM 

```{r}
# Scalamos los datos
scale2 <- function(x, na.rm = FALSE) (x - mean(x, na.rm = na.rm)) / sd(x, na.rm)
df_scaled <- dfs %>% 
  mutate_at(c("ba", "density", "dem", "slope", "aspect", "twi", "sh", "sh_c2", "n_strata"), ~scale2(.x, na.rm = TRUE)) %>% 
  filter(!is.na(wt_lid))
```


#### Modelo GLM 
- Buscar el mejor modelo basado en BIC 


```{r}
# Datos no scalados 
m0 <- glm(wt_lid ~ ba + density + dem + slope + aspect + twi + sh_c2 + n_strata, 
          family = "gaussian", data = df)


# Buscar el mejor modelo
### AIC or BIC  
# https://rstudio-pubs-static.s3.amazonaws.com/2897_9220b21cfc0c43a396ff9abf122bb351.html


set.seed(1234)
select_m0 <- glmulti(wt_lid ~ ba*density*dem*twi*sh_c2, data = df,
             level= 2,
        chunk = 1, chunks = 4,
        method = "ga",
        crit = "bic", 
        family = "gaussian", 
        marginality = TRUE,
        confsetsize = 5, 
        plotty = FALSE, report = FALSE)


summary(select_m0@objects[[1]]) 

# Best Model 
m <- glm(wt_lid ~ ba + density + dem + sh_c2 + ba:sh_c2 , 
          family = "gaussian", data = df)


tm <- tabglm(m, columns = c("beta.se",  "test", "p")) 
names(tm) <- c("Variable", "Estimate", "Zvalue", "pvalue") 


tablita_auxiliar <- data.frame(
  Variable = c("DegreeFreedom", "AIC", "BIC", "DevianceExplained"), 
  Estimate = as.character(c(df.residual(m), round(AIC(m),0), round(BIC(m), 0), 
round( ((m$null.deviance - m$deviance) / m$null.deviance),3))),
  Zvalue = "", pvalue = ""
)

tm <- bind_rows(tm, tablita_auxiliar)

write.csv(tm, here::here("data/best_glm_parameters.csv"))
```

```{r, results='asis'}
stargazer(m)
```

```{r}
stargazer(m, type="html")

# How many variance explained 
(m$null.deviance - m$deviance)/m$null.deviance*100

## diagnostics 
diagnosis_m <- simulateResiduals(m, seed = 123, n=1000, plot=TRUE)

testUniformity(diagnosis_m)
testDispersion(diagnosis_m)
```

# Predicted values GLM selected 
```{r}
#devtools::install_github("cardiomoon/ggiraphExtra")
# wt_lid ~ ba + density + dem + sh_c2 + ba:sh_c2
plot_model(m, sort.est = TRUE, type="std2")

ytitle <- expression(paste(W[total], " (Mg ", ha^-1,")"))
batitle <- expression(paste("Basal Area (",m^2, " ", ha^-1,")"))
demtitle <- "Elevation (m)"
densitytitle <- expression(paste("Tree density (trees ", ha^-1, ")"))
shtitle <- "Shannon structural diversity index"

# pdf(here::here("/fig/glm_wtotal.pdf"), width=7, height = 7)
png(here::here("/fig/glm_wtotal.png"), width=3000, height=3000, res=500, pointsize = 12)
par(mfrow=c(2,2),
    mar = c(4,4.5,2,2))
visreg(m, ylab = ytitle, "ba", xlab = batitle)
visreg(m, ylab = ytitle, "dem", xlab = demtitle)
visreg(m, ylab = ytitle, "density", xlab = densitytitle)
visreg(m, ylab = ytitle, "sh_c2", xlab = shtitle)
dev.off()
```

```{r}
# Plots interactions
visreg(m, "density", by="sh_c2")
visreg(m, "dem", by="sh_c2")
visreg(m, "ba", by="sh_c2")
visreg(m, "sh_c2", by="ba")
```


```{r}
p_ba <- visreg(m, ylab = ytitle, "ba", xlab = batitle, gg = TRUE, fill.par=list(fill="#008DFF33"))+
  theme_bw() + theme(panel.grid = element_blank())
                      
p_dem <- visreg(m, ylab = ytitle, "dem", xlab = demtitle, gg=TRUE,
                fill.par=list(fill="#008DFF33")) +
  theme_bw() + theme(panel.grid = element_blank()) 
p_den <- visreg(m, ylab = ytitle, "density", xlab = densitytitle, gg=TRUE, 
                fill.par=list(fill="#008DFF33")) +
  theme_bw() + theme(panel.grid = element_blank()) 
p_sh <- visreg(m, ylab = ytitle, "sh_c2", xlab = shtitle, gg=TRUE, fill.par=list(fill="#008DFF33")) +
  theme_bw() + theme(panel.grid = element_blank()) 


p_bash <- visreg(m, "sh_c2", by="ba", breaks=c(10, 25, 50), gg=TRUE,
       fill.par=list(fill="#008DFF33")) + 
  xlab(shtitle) + ylab(ytitle) + theme_bw() + 
  theme(
    panel.grid = element_blank(), 
    strip.background = element_blank()
  )

p_upper <- p_ba + p_dem + p_den + p_sh + plot_layout(nrow=2)

plotitos <- p_upper / p_bash+ plot_layout(ncol=1, heights = c(5,2.5)) + plot_annotation(tag_levels = "a") 


ggsave(filename=here::here("fig/glm_effects.pdf"), 
       plot=plotitos, width=5, height = 6, dpi = 500) 


```












# Surface responses 

```{r}
batitle_pers <- "\n\nBasal Area \n(m2 ha-1)"
wt_title <- "\n\nW total \n(Mg ha-1)"

png(here::here("/fig/glm_wtotal_surface.png"), width=1500, height=500, res=200)
par(mfrow=c(1,3),
    mar = c(5,0,0,0))
visreg2d(m, "dem", "ba", scale = "response", plot.type = "persp", theta = -45, phi =30,
         xlab = "\nElevation (m)", ylab = batitle_pers, zlab = wt_title,
         cex.lab = 1, cex.axis = 0.7, color = "green", shade =.4)

visreg2d(m,  "density", "ba", scale = "response", plot.type = "persp", theta = -45, phi = 30, 
         xlab = "\n\nTree density \n(trees ha-1)", ylab = batitle_pers, zlab = wt_title,
         cex.lab = 1, cex.axis = 0.7, color = "green", shade =.4)

visreg2d(m,   "sh_c2", "ba", scale = "response", plot.type = "persp", theta = -39, phi= 30, 
         xlab = "\n\nShannon \nstructural index ", ylab = batitle_pers, zlab = wt_title, 
         cex.lab = 1, cex.axis = 0.7, color = "green", shade =.4)
dev.off()

```



# Otras variables 

## Wr 
```{r}
set.seed(1234)
select_wr <- glmulti(wr_lid ~ ba*density*dem*twi*sh_c2, data = df,
             level= 2,
        chunk = 1, chunks = 4,
        method = "ga",
        crit = "bic", 
        family = "gaussian", 
        marginality = TRUE,
        confsetsize = 5, 
        plotty = FALSE, report = FALSE)

summary(select_wr@objects[[1]]) 


# Best Model 
mwr <- glm(wr_lid ~ ba + density + dem + sh_c2 + ba:sh_c2 , 
          family = "gaussian", data = df)


tmwr <- tabglm(mwr, columns = c("beta.se",  "test", "p")) 
names(tmwr) <- c("Variable", "Estimate", "Zvalue", "pvalue") 


tablita_auxiliar_wr <- data.frame(
  Variable = c("DegreeFreedom", "AIC", "BIC", "DevianceExplained"), 
  Estimate = as.character(c(df.residual(mwr), round(AIC(mwr),0), round(BIC(mwr), 0), 
round( ((mwr$null.deviance - mwr$deviance) / mwr$null.deviance),3))),
  Zvalue = "", pvalue = ""
)

tmwr <- bind_rows(tmwr, tablita_auxiliar_wr)

write.csv(tmwr, here::here("data/best_glm_parameters_wr.csv"))
```



## Wr 
```{r}
set.seed(1234)
select_ws <- glmulti(ws_lid ~ ba*density*dem*twi*sh_c2, data = df,
             level= 2,
        chunk = 1, chunks = 4,
        method = "ga",
        crit = "bic", 
        family = "gaussian", 
        marginality = TRUE,
        confsetsize = 5, 
        plotty = FALSE, report = FALSE)

summary(select_ws@objects[[1]]) 


# Best Model 
mws <- glm(ws_lid ~ ba + density + dem + sh_c2 + ba:sh_c2 , 
          family = "gaussian", data = df)


tmws <- tabglm(mws, columns = c("beta.se",  "test", "p")) 
names(tmws) <- c("Variable", "Estimate", "Zvalue", "pvalue") 


tablita_auxiliar_ws <- data.frame(
  Variable = c("DegreeFreedom", "AIC", "BIC", "DevianceExplained"), 
  Estimate = as.character(c(df.residual(mws), round(AIC(mws),0), round(BIC(mws), 0), 
round( ((mws$null.deviance - mws$deviance) / mws$null.deviance),3))),
  Zvalue = "", pvalue = ""
)

tmws <- bind_rows(tmws, tablita_auxiliar_ws)

write.csv(tmws, here::here("data/best_glm_parameters_ws.csv"))
```











```{r, eval=FALSE}
#Old codes 




# BestGLM 
# 
# 
# # Model 
# # wt_lid ~ ba + density + dem + slope + aspect + twi + sh_c2 
# 
# Xy <- df %>% 
#   dplyr::select(ba, density, dem, slope, aspect, twi, sh_c2, n_strata, wt_lid) %>% as.data.frame() %>% 
#   filter(!is.na(wt_lid))
# X <- Xy[,1:7]
# y <- Xy[,8]
# out <- summary(regsubsets(x = X, y = y, nvmax=ncol(X),
#                           method = "exhaustive"))
# 
# o <- cbind(out$which, rsq = out$rsq, rss = out$rss, 
#       adjr2 = out$adjr2, bic = out$bic)
# 
# 
# mejor <- bestglm(Xy, family = gaussian, IC="AIC", TopModels = 15)
# mejor$BestModels
# 



############### Surface responses Manual
# 
# # BA 
# mydata <- data.frame(ba = seq(0, 95, by = 1), dem = 1750, density = 500)
# p0 <- predict(m0best, newdata=mydata, type = "response", se = TRUE)
# 
# plot(x = Xy$ba, y = Xy$wt_lid, type = "n", xlab = "Basal Area", ylab = "Wtotal")
# points(x = Xy$ba, y = Xy$wt_lid, pch = 19, cex=0.5)
# lines(x=mydata$ba, y = p0$fit) 
# lines(x =mydata$ba, y = p0$fit  + 2*p0$se.fit, lty=2)
# lines(x =mydata$ba, y = p0$fit  - 2*p0$se.fit, lty=2)
# 
# # DEM 
# mydata <- data.frame(dem = seq(1300, 2000, by = 10), ba = 25, density = 500)
# p0 <- predict(m0best, newdata=mydata, type = "response", se = TRUE)
# 
# plot(x = Xy$dem, y = Xy$wt_lid, type = "n", xlab = "Elevation", ylab = "Wtotal")
# points(x = Xy$dem, y = Xy$wt_lid, pch = 19, cex=0.5)
# lines(x=mydata$dem, y = p0$fit) 
# lines(x =mydata$dem, y = p0$fit  + 2*p0$se.fit, lty=2)
# lines(x =mydata$dem, y = p0$fit  - 2*p0$se.fit, lty=2)
# 
# 
# # density 
# mydata <- data.frame(dem = 1750, ba = 25, density = seq(0, 3000, by = 25))
# p0 <- predict(m0best, newdata=mydata, type = "response", se = TRUE)
# 
# plot(x = Xy$density, y = Xy$wt_lid, type = "n", xlab = "Density", ylab = "Wtotal")
# points(x = Xy$density, y = Xy$wt_lid, pch = 19, cex=0.5)
# lines(x=mydata$density, y = p0$fit) 
# lines(x =mydata$density, y = p0$fit  + 2*p0$se.fit, lty=2)
# lines(x =mydata$density, y = p0$fit  - 2*p0$se.fit, lty=2)

# 
# # Obtener que color de sombra se utiliza 
# sombra.col <- trellis.par.get("shade.colors")
# ## Cambiar la transparencia del grafico 
# sombra.col$alpha <-.3
# ## Cambiar la paleta del sombreado
# sombra.col$palette <- function(irr, ref,
# height, w = 0.5) {grey(w * irr + (1 - w) * (1 - (1 - ref)^0.4))}
# ## Set los nuevos valores de shade
# trellis.par.set("shade.colors",sombra.col)
# 
# 
# # 3d plot BA elev 
# 
# # Creamos un conjunto de datos para los predichos
# nuevos.datos <- expand.grid(dem = seq(from=1300, to=2000, by=10),
#                             ba = seq(0, 95, by = 1), density = 500)
# # Calculamos los predichos 
# nuevos.datos$predichos <- predict(m0best, newdata=nuevos.datos, type="response")
# 
# 
# plot_elev_ba <- wireframe(predichos ~ dem * ba,
# 		data=nuevos.datos, screen= list(z=-35, x= -60), shade=T, 
# 		scales = list(arrows = TRUE),
# 		zlab = list(label = "Wt"),
# 		ylab = list(label = "BA"),
# 		xlab = list(label = "Elevation"),
# 		strip = strip.custom(bg=gray.colors(1,0.95)))
# 
# 
# # 3d plot BA density 
# 
# # Creamos un conjunto de datos para los predichos
# nuevos.datos <- expand.grid(dem = 1750,
#                             ba = seq(0, 95, by = 20), 
#                             density = seq(0, 3000, by = 100))
# # Calculamos los predichos 
# nuevos.datos$predichos <- predict(m0best, newdata=nuevos.datos, type="response")
# 
# plot_den_ba <- wireframe(predichos ~ density * ba,
# 		data=nuevos.datos, screen= list(z=-35, x= -60), shade=T, 
# 		scales = list(arrows = TRUE),
# 		zlab = list(label = "Wt"),
# 		ylab = list(label = "BA"),
# 		xlab = list(label = "Tree density"),
# 		strip = strip.custom(bg=gray.colors(1,0.95)),
# 				panel.3d.wireframe =
#             function(x, y, z,
#                      xlim, ylim, zlim,
#                      xlim.scaled, ylim.scaled, zlim.scaled,
#                      ...) {
#               panel.3dwire(x = x, y = y, z = z,
#                            xlim = xlim,
#                            ylim = ylim,
#                            zlim = zlim,
#                            xlim.scaled = xlim.scaled,
#                            ylim.scaled = ylim.scaled,
#                            zlim.scaled = zlim.scaled,
#                            col = "gray",
#                            ...)
#             })
# 
# 
# 
# # 3d plot elev density 
# 
# # Creamos un conjunto de datos para los predichos
# nuevos.datos <- expand.grid(dem = seq(1300, 2000, by = 50), 
#                             ba = 25,
#                             density = seq(0, 3000, by = 50))
# # Calculamos los predichos 
# nuevos.datos$predichos <- predict(m0best, newdata=nuevos.datos, type="response")
# 
# plot_dem_den <-
# wireframe(predichos ~ dem * density ,
# 		data=nuevos.datos, screen= list(z=-35, x= -50), shade=T, 
# 		scales = list(arrows = TRUE),
# 		zlab = list(label = "Wt"),
# 		#ylab = list(label = "BA"),
# 		#xlab = list(label = "Tree density"),
# 		strip = strip.custom(bg=gray.colors(1,0.95)),
# 		panel.3d.wireframe =
#             function(x, y, z,
#                      xlim, ylim, zlim,
#                      xlim.scaled, ylim.scaled, zlim.scaled,
#                      ...) {
#               panel.3dwire(x = x, y = y, z = z,
#                            xlim = xlim,
#                            ylim = ylim,
#                            zlim = zlim,
#                            xlim.scaled = xlim.scaled,
#                            ylim.scaled = ylim.scaled,
#                            zlim.scaled = zlim.scaled,
#                            col = "gray",
#                            ...)
#             })
# 
```













   







