---
title: "Import data from ODS"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE, warning=FALSE}
source("./load_pkgs.R")
```

```{r}
sheet_name <- "1_DASOMETRICO"

# list ods files 
ods_file_names <- here::here("raw_data/robledal_life/") %>%
  list.files() %>%
  .[str_detect(., ".ods")] 

# Read tree data 
df_dbh <- ods_file_names %>% 
  purrr::map_dfr(function(file_name){ # iterate through each file name
    daso <- read_ods(paste0(here::here("raw_data/robledal_life/"), file_name),
                          sheet = "1_DASOMETRICO") %>%
      as_tibble(.name_repair = "unique") %>% # Name variable col 7
      mutate(code = str_remove(file_name, "_c1_forestal.ods"))
    }) %>% 
  filter(is.na(`...7`)) %>% 
  dplyr::select(-CUADRANTE, sp = ESPECIE, -`...7`, 
                dbh1 = "Dnor (cm) 1", dbh2 = "Dnor (cm) 2", 
                dbase1 ="Dbas (cm) 1", dbase2 = "Dbas (cm) 2")
      
    
# Read tipo data 
df_tipo <- ods_file_names %>% 
  purrr::map_dfr(function(file_name){ # iterate through each file name
    daso <- read_ods(paste0(here::here("raw_data/robledal_life/"), file_name),
                          sheet = "2_EJEMPLARES_TIPO") %>%
      as_tibble(.name_repair = "unique") %>% # Name variable col 7
      mutate(code = str_remove(file_name, "_c1_forestal.ods"))
    }) %>% 
   dplyr::select(sp = Especie, h = "Altura (m)", 
                dbh1 = "D.nor (cm) 1", dbh2 = "D.nor (cm) 2", 
                dbase1 ="D.bas (cm) 1", dbase2 = "D.bas (cm) 2", 
                code) 
  
df_tipo <- df_tipo %>% filter(str_detect(code, "CAN"))
    
    
     
  ods_file_names %>%
  purrr::map(function(file_name){ # iterate through each file name
  assign(x = str_remove(file_name, "_c1_forestal.ods"), 
         value = read_ods(paste0(here::here("raw_data/robledal_life/"), file_name),
                          sheet = "1_DASOMETRICO"),
         envir = .GlobalEnv)
})
  
    
    
    
  assign(x = str_remove(file_name, "_c1_forestal.ods"), 
         value = read_ods(paste0(here::here("raw_data/robledal_life/"), file_name),
                          sheet = "1_DASOMETRICO"),
         envir = .GlobalEnv)
})



  
  
f <- "CAN_CON_22_c1_forestal.ods"


original_code <- str_sub(f,end=10)

daso <- read_ods(here::here("raw_data/robledal_life/CAN_CON_22_c1_forestal.ods"), 
              sheet = sheet_name) %>% 

  files
  





et <- read_ods(here::here("raw_data/robledal_life/CAN_CON_22_c1_forestal.ods"), 
              sheet = "2_EJEMPLARES_TIPO")

read_od
```

